using System.Collections.Generic;
using System.IO;

namespace Gma.CodeCloud.Base.TextAnalyses.Extractors.Code
{
    public class JavaExtractor : CodeExtractorBase
    {
        public JavaExtractor(IEnumerable<FileInfo> files, IProgressIndicator progressIndicator) 
            : base(files, progressIndicator)
        {
        }

        protected override bool CanSkipFile(string line)
        {
            return
                line.Contains("[TestFixture]") ||
                line.Contains("This code was generated by a tool.");
        }


        protected override string IgnoreRegionsAndUsings(string text)
        {
            if (text.StartsWith("import")) return string.Empty;
            if (text.StartsWith("package")) return string.Empty;
            return text;
        }
    }
}
